# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
## config/database.yml ##

development:
  adapter: postgresql
  encoding: utf8
  database: development
  host: localhost
  pool: 5
  username: psql_dev
  password: "ushilove"

test:
  adapter: postgresql
  encoding: utf8
  database: test
  host: localhost
  pool: 5
  username: psql_test
  password: "ushilove"

production:
  adapter: postgresql
  encoding: utf8
  database: production
  host: localhost
  pool: 5
  username: alicianguyen
  password: "ushilove"